# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# pointing to ansible 2.10 tag on github; ansible changed to ansible-base on pypi
# so to avoid complicating things for now, use git hash
# TODO: point to ansible==2.10 when it comes out so we don't need to install collections separately

jobs:

- job: Mac
  steps:
  - template: azure-pipelines-steps.yml
  pool:
    vmImage: macOS-10.14
  strategy:
    matrix:
      Mito27_27:
        python.version: '2.7.18'
        MODE: mitogen
        VER: git+https://github.com/ansible/ansible.git@v2.10.0
      Ans210_27:
        python.version: '2.7.18'
        MODE: localhost_ansible
        VER: git+https://github.com/ansible/ansible.git@v2.10.0


- job: Linux
  pool:
    vmImage: "Ubuntu 18.04"
  steps:
  - template: azure-pipelines-steps.yml
  strategy:
    matrix:
      #
      # Confirmed working
      #
      Mito27Debian_27:
        python.version: '2.7'
        MODE: mitogen
        DISTRO: debian
        VER: git+https://github.com/ansible/ansible.git@v2.10.0

      #MitoPy27CentOS6_26:
        #python.version: '2.7'
        #MODE: mitogen
        #DISTRO: centos6

      Mito36CentOS6_26:
        python.version: '3.6'
        MODE: mitogen
        DISTRO: centos6
        VER: git+https://github.com/ansible/ansible.git@v2.10.0

      Mito37Debian_27:
        python.version: '3.7'
        MODE: mitogen
        DISTRO: debian
        VER: git+https://github.com/ansible/ansible.git@v2.10.0

      #Py26CentOS7:
        #python.version: '2.7'
        #MODE: mitogen
        #DISTRO: centos6

      #DebOps_2460_27_27:
        #python.version: '2.7'
        #MODE: debops_common
        #VER: 2.4.6.0

      #DebOps_262_36_27:
        #python.version: '3.6'
        #MODE: debops_common
        #VER: 2.6.2

      #Ansible_2460_26:
        #python.version: '2.7'
        #MODE: ansible
        #VER: 2.4.6.0

      #Ansible_262_26:
        #python.version: '2.7'
        #MODE: ansible
        #VER: 2.6.2

      #Ansible_2460_36:
        #python.version: '3.6'
        #MODE: ansible
        #VER: 2.4.6.0

      #Ansible_262_36:
        #python.version: '3.6'
        #MODE: ansible
        #VER: 2.6.2

      #Vanilla_262_27:
        #python.version: '2.7'
        #MODE: ansible
        #VER: 2.6.2
        #DISTROS: debian
        #STRATEGY: linear

      # fails with error
      # exception:   File "/tmp/venv/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 129, in cleanup
      # exception:     self._remove_tmp_path(self._connection._shell.tmpdir)
      # exception: AttributeError: 'get_with_context_result' object has no attribute '_shell'
      # TODO: looks like a bug on Ansible's end with this release? Maybe 2.10.1 will fix it
      # Ansible_210_27:
      #   python.version: '2.7'
      #   MODE: ansible
      #   VER: git+https://github.com/ansible/ansible.git@v2.10.0

      # fails with error
      # exception:   File "/tmp/venv/lib/python3.5/site-packages/ansible/plugins/action/__init__.py", line 129, in cleanup
      # exception:     self._remove_tmp_path(self._connection._shell.tmpdir)
      # exception: AttributeError: 'get_with_context_result' object has no attribute '_shell'
      # TODO: looks like a bug on Ansible's end with this release? Maybe 2.10.1 will fix it
      # Ansible_210_35:
      #   python.version: '3.5'
      #   MODE: ansible
      #   VER: git+https://github.com/ansible/ansible.git@v2.10.0
