# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# User defined variables are also injected as environment variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables#environment-variables
#variables:
  #ANSIBLE_VERBOSITY: 3

jobs:

- job: Mac
  # vanilla Ansible is really slow
  timeoutInMinutes: 120
  steps:
  - template: azure-pipelines-steps.yml
  pool:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    vmImage: macOS-10.15
  strategy:
    matrix:
      Mito27_27:
        python.version: '2.7'
        tox.env: py27-mode_mitogen

      # TODO: test python3, python3 tests are broken
      Local_Py27:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible{2.10,3,4}

      # NOTE: this hangs when ran in Ubuntu 18.04
      Vanilla_Py27:
        python.version: '2.7'
        tox.env: py27-mode_localhost-ansible{2.10,3,4}
        STRATEGY: linear
        ANSIBLE_SKIP_TAGS: resource_intensive


- job: Linux
  pool:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
    vmImage: "Ubuntu 18.04"
  steps:
  - template: azure-pipelines-steps.yml
  strategy:
    matrix:
      Mito_Py27:
        python.version: '2.7'
        tox.env: py27-mode_mitogen-distro_{centos6,centos7,centos8,debian9,debian10,debian11,ubuntu1604,ubuntu1804,ubuntu2004}

      Mito_Py36:
        python.version: '3.6'
        tox.env: py36-mode_mitogen-distro_{centos6,centos7,centos8,debian9,debian10,debian11,ubuntu1604,ubuntu1804,ubuntu2004}

      Mito_Py39:
        python.version: '3.9'
        tox.env: py39-mode_mitogen-distro_{centos6,centos7,centos8,debian9,debian10,debian11,ubuntu1604,ubuntu1804,ubuntu2004}

      #DebOps_2460_27_27:
        #python.version: '2.7'
        #MODE: debops_common
        #VER: 2.4.6.0

      #DebOps_262_36_27:
        #python.version: '3.6'
        #MODE: debops_common
        #VER: 2.6.2

      #Ansible_2460_26:
        #python.version: '2.7'
        #MODE: ansible
        #VER: 2.4.6.0

      #Ansible_262_26:
        #python.version: '2.7'
        #MODE: ansible
        #VER: 2.6.2

      #Ansible_2460_36:
        #python.version: '3.6'
        #MODE: ansible
        #VER: 2.4.6.0

      #Ansible_262_36:
        #python.version: '3.6'
        #MODE: ansible
        #VER: 2.6.2

      #Vanilla_262_27:
        #python.version: '2.7'
        #MODE: ansible
        #VER: 2.6.2
        #DISTROS: debian
        #STRATEGY: linear

      Ansible_Py27:
        python.version: '2.7'
        tox.env: py27-mode_ansible-ansible{2.10,3,4}

      Ansible_Py36:
        python.version: '3.6'
        tox.env: py36-mode_ansible-ansible{2.10,3,4}

      Ansible_Py39:
        python.version: '3.9'
        tox.env: py39-mode_ansible-ansible{2.10,3,4}
