
parameters:
  name: ''
  pool: ''
  sign: false

steps:
- task: UsePythonVersion@0
  displayName: Install python
  inputs:
    versionSpec: '$(python.version)'

- script: python -mpip install tox
  displayName: Install tooling

- script: tox -e "$(tox.env)"
  displayName: "Run tests"
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
